import pandas as pd

d = pd.read_csv("sqldatafiles/meals.csv")

d["cuisine"]=['North Indian',
'North Indian',
'North Indian',
'North Indian',
'Chinese',
'Indian',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'Indian',
'North Indian',
'South Indian',
'Chinese',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'Indian',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'Indian',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'Indian',
'Indian',
'Indian',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'Indian',
'North Indian',
'Indian',
'Indian',
'Indian',
'North Indian',
'North Indian',
'North Indian',
'Indian',
'Indian',
'Indian',
'Chinese',
'Chinese',
'Indian',
'Chinese',
'Chinese',
'Chinese',
'South Indian',
'North Indian',
'North Indian',
'North Indian',
'Indian',
'North Indian',
'North Indian',
'North Indian',
'North Indian',
'South Indian',
'Indian',
'South Indian',
'South Indian',
'South Indian',
'Indian',
'South Indian',
'South Indian',
'South Indian',
'South Indian',
'South Indian',
'South Indian',
'South Indian',
'South Indian',
'South Indian',
'Indian',
'Indian',
'North Indian',
'North Indian',
'North Indian',
'Indian',
'Indian',
'Indian',
'Indian']

d["ingredients"]=['paneer, yogurt, spices, onion',
'potato, peas, flour, spices',
'onion, gram flour, spices, oil',
'spinach, potato, peas, spices',
'cauliflower, soy sauce, garlic, chili',
'corn, flour, chili, spices',
'yogurt, paneer, flour, spices',
'potato, flour, spices, oil',
'chicken, yogurt, spices, lemon',
'minced meat, onion, spices, skewer',
'fish, gram flour, spices, lemon',
'prawns, chili, garlic, oil',
'mutton, lentils, spices, onion',
'chicken, chili, curry leaves, oil',
'chicken, chili, soy sauce, garlic',
'chicken, yogurt, spices, lemon',
'black lentils, butter, cream, spices',
'spinach, paneer, onion, spices',
'chickpeas, flour, spices, oil',
'paneer, potato, cream, spices',
'potato, cauliflower, onion, spices',
'eggplant, onion, tomato, spices',
'okra, onion, spices, oil',
'vegetables, cream, nuts, spices',
'chicken, tomato, butter, cream',
'mutton, yogurt, chili, spices',
'fish, coconut, chili, tamarind',
'chicken, yogurt, onion, spices',
'rice, chicken, yogurt, spices',
'mutton, peas, onion, spices',
'chicken, tomato, cream, spices',
'mutton, chili, yogurt, spices',
'wheat flour, water, salt, oil',
'flour, butter, salt, water',
'flour, garlic, butter, salt',
'rice, cumin, ghee, salt',
'rice, chicken, spices, yogurt',
'rice, mutton, yogurt, spices',
'milk, flour, sugar, ghee',
'carrot, milk, sugar, ghee',
'rice, milk, sugar, cardamom',
'tea, milk, sugar, spices',
'yogurt, water, sugar, spices',
'cumin, mint, water, lemon',
'kidney beans, rice, onion, spices',
'chickpea flour, yogurt, spices, oil',
'gram flour, onion, spices, ghee',
'potato, flour, spices, ghee',
'paneer, flour, spices, ghee',
'bread, milk, sugar, ghee',
'milk, sugar, fruits, cream',
'mint, coriander, chili, lemon',
'yogurt, cucumber, cumin, salt',
'lentils, flour, salt, oil',
'onion, lemon, chili, salt',
'wheat flour, salt, water, ghee',
'spinach, flour, salt, oil',
'fenugreek, flour, salt, oil',
'potato, chili, lemon, spices',
'semolina, tamarind, potato, chili',
'yogurt, lentils, spices, oil',
'rice, puffed rice, tamarind, onion',
'rice, vegetables, soy sauce, chili',
'rice, chili, garlic, soy sauce',
'rice, paneer, onion, spices',
'rice, chicken, soy sauce, chili',
'noodles, chicken, soy sauce, chili',
'noodles, vegetables, chili, soy sauce',
'cauliflower, chili, curry leaves, flour',
'flour, mint, salt, oil',
'flour, butter, salt, onion',
'flour, potato, onion, butter',
'mushroom, onion, tomato, spices',
'spinach, corn, cream, spices',
'paneer, peas, onion, tomato',
'potato, yogurt, onion, spices',
'rice, dry fruits, milk, saffron',
'rice, vegetables, ghee, spices',
'egg, onion, tomato, spices',
'flour, ghee, salt, oil',
'rice, coconut, curry leaves, spices',
'rice, tomato, chili, spices',
'rice, lemon, curry leaves, chili',
'rice, yogurt, curry leaves, spices',
'rice, lentils, potato, spices',
'rice, lentils, spices, oil',
'lentils, onion, chili, oil',
'tamarind, chili, curry leaves, spices',
'lentils, tamarind, vegetables, spices',
'rice, lentils, onion, chili',
'rice, coconut, yeast, salt',
'rice, coconut, sugar, banana',
'black chickpeas, onion, coconut, spices',
'vegetables, coconut, curry leaves, yogurt',
'yam, banana, coconut, yogurt',
'yogurt, cucumber, chili, spices',
'rice, tomato, curry leaves, chili',
'okra, onion, chili, spices',
'flour, fenugreek, chili, spices',
'wheat, eggplant, potato, chili']

print(d.head())

yn = input("save?")
if yn == 'y':
    d.to_csv("meals.csv")